import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import ResponsiveNav from "@/components/Navbar/ResponsiveNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Velisa Africa Academy - Landing Page",
  description: "Generated by Next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
